CREATE CONSTRAINT country_name IF NOT EXISTS
FOR (c:Country)
REQUIRE c.name IS UNIQUE;

CREATE CONSTRAINT threatgroup_id IF NOT EXISTS
FOR (t:ThreatGroup)
REQUIRE t.id IS UNIQUE;

CREATE CONSTRAINT malware_id IF NOT EXISTS
FOR (m:Malware)
REQUIRE m.id IS UNIQUE;

CREATE CONSTRAINT technique_id IF NOT EXISTS
FOR (t:Technique)
REQUIRE t.id IS UNIQUE;

CREATE CONSTRAINT cve_id IF NOT EXISTS
FOR (c:CVE)
REQUIRE c.id IS UNIQUE;

CREATE CONSTRAINT product_id IF NOT EXISTS
FOR (p:Product)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT vendor_id IF NOT EXISTS
FOR (v:Vendor)
REQUIRE v.id IS UNIQUE;

CREATE CONSTRAINT patch_id IF NOT EXISTS
FOR (p:Patch)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT industry_id IF NOT EXISTS
FOR (i:Industry)
REQUIRE i.id IS UNIQUE;